// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToniEmprega.Data;

#nullable disable

namespace ToniEmprega.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212204906_Ajustes")]
    partial class Ajustes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToniEmprega.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ano_Letivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Numero_Aluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Avaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Candidatura")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Decisao_Avaliacao")
                        .HasColumnType("int");

                    b.Property<int>("Id_Professor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Candidatura");

                    b.HasIndex("Id_Decisao_Avaliacao");

                    b.HasIndex("Id_Professor");

                    b.ToTable("Avaliacoes_Professor", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_Candidatura")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Estado_Candidatura")
                        .HasColumnType("int");

                    b.Property<int>("Id_Oferta")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Aluno");

                    b.HasIndex("Id_Estado_Candidatura");

                    b.HasIndex("Id_Oferta");

                    b.ToTable("Candidaturas", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.CandidaturaFicheiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho_Ficheiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Upload")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Candidatura")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Ficheiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Ficheiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Candidatura");

                    b.ToTable("Candidaturas_Ficheiros", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.DecisaoAvaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Decisoes_Avaliacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Aprovado"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Rejeitado"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Necessita de Revisão"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoCandidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Candidatura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Em Análise"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Aprovada"
                        },
                        new
                        {
                            Id = 4,
                            Designacao = "Rejeitada"
                        },
                        new
                        {
                            Id = 5,
                            Designacao = "Cancelada"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Oferta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Ativa"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Expirada"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Preenchida"
                        },
                        new
                        {
                            Id = 4,
                            Designacao = "Desativada"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Validacao_Documento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Aprovado"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Rejeitado"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Validacao_Utilizador", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Aprovado"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Rejeitado"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data_Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Publicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Estado_Oferta")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Tipo_Oferta")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Empresa");

                    b.HasIndex("Id_Estado_Oferta");

                    b.HasIndex("Id_Tipo_Oferta");

                    b.ToTable("Ofertas", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Numero_Professor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Oferta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Estágio curricular ou profissional",
                            Designacao = "Estágio"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Contrato de trabalho",
                            Designacao = "Emprego"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Participação em projeto",
                            Designacao = "Projeto"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Utilizador", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Aluno"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Professor"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Empresa"
                        },
                        new
                        {
                            Id = 4,
                            Designacao = "Utilizador Normal"
                        },
                        new
                        {
                            Id = 5,
                            Designacao = "Administrador"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoValidacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Validacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Cartão de Estudante"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Bilhete de Identidade"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Cartão de Cidadão"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Estado_Validacao_Utilizador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tipo_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Palavra_Passe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Estado_Validacao_Utilizador");

                    b.HasIndex("Id_Tipo_Utilizador");

                    b.ToTable("Utilizadores", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.UtilizadorNormal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documentacao_Identificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Utilizadores_Normais", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.ValidacaoIdentidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data_Validacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ficheiro_Prova")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Estado_Validacao_Documento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tipo_Validacao")
                        .HasColumnType("int");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Estado_Validacao_Documento");

                    b.HasIndex("Id_Tipo_Validacao");

                    b.HasIndex("Id_Utilizador");

                    b.ToTable("Validacoes_Identidade", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.Admin", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Admin", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Aluno", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Aluno", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.HasOne("ToniEmprega.Models.Candidatura", "Candidatura")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Id_Candidatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.DecisaoAvaliacao", "DecisaoAvaliacao")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Id_Decisao_Avaliacao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.Professor", "Professor")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Id_Professor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("DecisaoAvaliacao");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.HasOne("ToniEmprega.Models.Aluno", "Aluno")
                        .WithMany("Candidaturas")
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoCandidatura", "EstadoCandidatura")
                        .WithMany("Candidaturas")
                        .HasForeignKey("Id_Estado_Candidatura")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.Oferta", "Oferta")
                        .WithMany("Candidaturas")
                        .HasForeignKey("Id_Oferta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("EstadoCandidatura");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("ToniEmprega.Models.CandidaturaFicheiro", b =>
                {
                    b.HasOne("ToniEmprega.Models.Candidatura", "Candidatura")
                        .WithMany("Ficheiros")
                        .HasForeignKey("Id_Candidatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");
                });

            modelBuilder.Entity("ToniEmprega.Models.Empresa", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Empresa", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.HasOne("ToniEmprega.Models.Empresa", "Empresa")
                        .WithMany("Ofertas")
                        .HasForeignKey("Id_Empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoOferta", "EstadoOferta")
                        .WithMany("Ofertas")
                        .HasForeignKey("Id_Estado_Oferta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.TipoOferta", "TipoOferta")
                        .WithMany("Ofertas")
                        .HasForeignKey("Id_Tipo_Oferta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("EstadoOferta");

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("ToniEmprega.Models.Professor", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Professor", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Utilizador", b =>
                {
                    b.HasOne("ToniEmprega.Models.EstadoValidacaoUtilizador", "EstadoValidacao")
                        .WithMany("Utilizadores")
                        .HasForeignKey("Id_Estado_Validacao_Utilizador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.TipoUtilizador", "TipoUtilizador")
                        .WithMany("Utilizadores")
                        .HasForeignKey("Id_Tipo_Utilizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoValidacao");

                    b.Navigation("TipoUtilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.UtilizadorNormal", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.UtilizadorNormal", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.ValidacaoIdentidade", b =>
                {
                    b.HasOne("ToniEmprega.Models.EstadoValidacaoDocumento", "EstadoValidacaoDocumento")
                        .WithMany("Validacoes")
                        .HasForeignKey("Id_Estado_Validacao_Documento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.TipoValidacao", "TipoValidacao")
                        .WithMany("Validacoes")
                        .HasForeignKey("Id_Tipo_Validacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithMany("ValidacoesIdentidade")
                        .HasForeignKey("Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoValidacaoDocumento");

                    b.Navigation("TipoValidacao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Aluno", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Ficheiros");
                });

            modelBuilder.Entity("ToniEmprega.Models.DecisaoAvaliacao", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("ToniEmprega.Models.Empresa", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoCandidatura", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoOferta", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoDocumento", b =>
                {
                    b.Navigation("Validacoes");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoUtilizador", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.Professor", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoOferta", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoUtilizador", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoValidacao", b =>
                {
                    b.Navigation("Validacoes");
                });

            modelBuilder.Entity("ToniEmprega.Models.Utilizador", b =>
                {
                    b.Navigation("ValidacoesIdentidade");
                });
#pragma warning restore 612, 618
        }
    }
}
