// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToniEmprega.Data;

#nullable disable

namespace ToniEmprega.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToniEmprega.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnoLetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("NumeroAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Candidatura")
                        .HasColumnType("int");

                    b.Property<int>("Id_Professor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Candidatura");

                    b.HasIndex("Id_Professor");

                    b.ToTable("AvaliacoesProfessores");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Estado_Candidatura")
                        .HasColumnType("int");

                    b.Property<int>("Id_Oferta")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Aluno");

                    b.HasIndex("Id_Estado_Candidatura");

                    b.HasIndex("Id_Oferta");

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoCandidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoCandidaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Em Análise"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Aprovada"
                        },
                        new
                        {
                            Id = 4,
                            Designacao = "Rejeitada"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoOfertas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Ativa"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Expirada"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Preenchida"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoValidacaoUtilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Aprovado"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Rejeitado"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Estado_Oferta")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Tipo_Oferta")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Empresa");

                    b.HasIndex("Id_Estado_Oferta");

                    b.HasIndex("Id_Tipo_Oferta");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("NumeroProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Utilizador")
                        .IsUnique();

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoOfertas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Estágio curricular",
                            Designacao = "Estágio"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Contrato de trabalho",
                            Designacao = "Emprego"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Projeto temporário",
                            Designacao = "Projeto"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUtilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designacao = "Aluno"
                        },
                        new
                        {
                            Id = 2,
                            Designacao = "Professor"
                        },
                        new
                        {
                            Id = 3,
                            Designacao = "Empresa"
                        },
                        new
                        {
                            Id = 4,
                            Designacao = "Administrador"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Estado_Validacao_Utilizador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tipo_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalavraPasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Estado_Validacao_Utilizador");

                    b.HasIndex("Id_Tipo_Utilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("ToniEmprega.Models.Aluno", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Aluno", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.HasOne("ToniEmprega.Models.Candidatura", "Candidatura")
                        .WithMany()
                        .HasForeignKey("Id_Candidatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("Id_Professor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.HasOne("ToniEmprega.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoCandidatura", "EstadoCandidatura")
                        .WithMany("Candidaturas")
                        .HasForeignKey("Id_Estado_Candidatura")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.Oferta", "Oferta")
                        .WithMany()
                        .HasForeignKey("Id_Oferta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("EstadoCandidatura");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("ToniEmprega.Models.Empresa", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Empresa", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.HasOne("ToniEmprega.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("Id_Empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoOferta", "EstadoOferta")
                        .WithMany("Ofertas")
                        .HasForeignKey("Id_Estado_Oferta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.TipoOferta", "TipoOferta")
                        .WithMany("Ofertas")
                        .HasForeignKey("Id_Tipo_Oferta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("EstadoOferta");

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("ToniEmprega.Models.Professor", b =>
                {
                    b.HasOne("ToniEmprega.Models.Utilizador", "Utilizador")
                        .WithOne()
                        .HasForeignKey("ToniEmprega.Models.Professor", "Id_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.Utilizador", b =>
                {
                    b.HasOne("ToniEmprega.Models.EstadoValidacaoUtilizador", "EstadoValidacao")
                        .WithMany("Utilizadores")
                        .HasForeignKey("Id_Estado_Validacao_Utilizador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToniEmprega.Models.TipoUtilizador", "TipoUtilizador")
                        .WithMany("Utilizadores")
                        .HasForeignKey("Id_Tipo_Utilizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoValidacao");

                    b.Navigation("TipoUtilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoCandidatura", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoOferta", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoUtilizador", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoOferta", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoUtilizador", b =>
                {
                    b.Navigation("Utilizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
