// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToniEmprega.Data;

#nullable disable

namespace ToniEmprega.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131004635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EstadoValidacaoUtilizadorId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUtilizadorId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoValidacaoUtilizadorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TipoUtilizadorId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisaoId")
                        .HasColumnType("int");

                    b.Property<string>("ProfessorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CandidaturaId");

                    b.HasIndex("DecisaoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("AvaliacoesProfessor");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoCandidaturaId")
                        .HasColumnType("int");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("EstadoCandidaturaId");

                    b.HasIndex("OfertaId");

                    b.HasIndex("UserId");

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("ToniEmprega.Models.CandidaturaFicheiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CandidaturaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFicheiro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CandidaturaId");

                    b.ToTable("CandidaturasFicheiros");
                });

            modelBuilder.Entity("ToniEmprega.Models.DecisaoAvaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("DecisoesAvaliacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aprovado"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rejeitado"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rever"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoCandidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosCandidatura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aceite"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rejeitada"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosOferta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ativa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Expirada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Removida"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosValidacaoDocumento");
                });

            modelBuilder.Entity("ToniEmprega.Models.EstadoValidacaoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosValidacaoUtilizador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aprovado"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rejeitado"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmpresaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoOfertaId")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TipoOfertaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstadoOfertaId");

                    b.HasIndex("TipoOfertaId");

                    b.HasIndex("UserId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposOferta");
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposUtilizador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aluno"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Empresa"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Professor"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Basic"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Moderator"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("ToniEmprega.Models.TipoValidacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposValidacao");
                });

            modelBuilder.Entity("ToniEmprega.Models.ValidacaoIdentidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoDocumento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoValidacaoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoValidacaoUtilizadorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoValidacaoId")
                        .HasColumnType("int");

                    b.Property<string>("UtilizadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoValidacaoDocumentoId");

                    b.HasIndex("EstadoValidacaoUtilizadorId");

                    b.HasIndex("TipoValidacaoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("ValidacoesIdentidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ToniEmprega.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ToniEmprega.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ToniEmprega.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToniEmprega.Models.ApplicationUser", b =>
                {
                    b.HasOne("ToniEmprega.Models.EstadoValidacaoUtilizador", "EstadoValidacaoUtilizador")
                        .WithMany()
                        .HasForeignKey("EstadoValidacaoUtilizadorId");

                    b.HasOne("ToniEmprega.Models.TipoUtilizador", "TipoUtilizador")
                        .WithMany()
                        .HasForeignKey("TipoUtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoValidacaoUtilizador");

                    b.Navigation("TipoUtilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.AvaliacaoProfessor", b =>
                {
                    b.HasOne("ToniEmprega.Models.Candidatura", "Candidatura")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.DecisaoAvaliacao", "Decisao")
                        .WithMany()
                        .HasForeignKey("DecisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.ApplicationUser", "Professor")
                        .WithMany("AvaliacoesProfessor")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("Decisao");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.HasOne("ToniEmprega.Models.ApplicationUser", "Aluno")
                        .WithMany("CandidaturasAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoCandidatura", "EstadoCandidatura")
                        .WithMany()
                        .HasForeignKey("EstadoCandidaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.Oferta", "Oferta")
                        .WithMany("Candidaturas")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.ApplicationUser", "User")
                        .WithMany("Candidaturas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("EstadoCandidatura");

                    b.Navigation("Oferta");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToniEmprega.Models.CandidaturaFicheiro", b =>
                {
                    b.HasOne("ToniEmprega.Models.Candidatura", "Candidatura")
                        .WithMany("Ficheiros")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.HasOne("ToniEmprega.Models.ApplicationUser", "Empresa")
                        .WithMany("OfertasEmpresa")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoOferta", "EstadoOferta")
                        .WithMany()
                        .HasForeignKey("EstadoOfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.TipoOferta", "TipoOferta")
                        .WithMany()
                        .HasForeignKey("TipoOfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.ApplicationUser", "User")
                        .WithMany("Ofertas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("EstadoOferta");

                    b.Navigation("TipoOferta");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToniEmprega.Models.ValidacaoIdentidade", b =>
                {
                    b.HasOne("ToniEmprega.Models.EstadoValidacaoDocumento", "EstadoDocumento")
                        .WithMany()
                        .HasForeignKey("EstadoValidacaoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.EstadoValidacaoUtilizador", "EstadoUtilizador")
                        .WithMany()
                        .HasForeignKey("EstadoValidacaoUtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.TipoValidacao", "TipoValidacao")
                        .WithMany()
                        .HasForeignKey("TipoValidacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToniEmprega.Models.ApplicationUser", "Utilizador")
                        .WithMany("ValidacoesIdentidade")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoDocumento");

                    b.Navigation("EstadoUtilizador");

                    b.Navigation("TipoValidacao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ToniEmprega.Models.ApplicationUser", b =>
                {
                    b.Navigation("AvaliacoesProfessor");

                    b.Navigation("Candidaturas");

                    b.Navigation("CandidaturasAluno");

                    b.Navigation("Ofertas");

                    b.Navigation("OfertasEmpresa");

                    b.Navigation("ValidacoesIdentidade");
                });

            modelBuilder.Entity("ToniEmprega.Models.Candidatura", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Ficheiros");
                });

            modelBuilder.Entity("ToniEmprega.Models.Oferta", b =>
                {
                    b.Navigation("Candidaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
